# Generated by Django 5.0.6 on 2024-06-22 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talon.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Talon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Ф.И.Ш.')),
                ('position', models.CharField(max_length=255, verbose_name='Лавозими')),
                ('date_received', models.DateField(verbose_name='Олинган санаси')),
                ('talon_number', models.CharField(max_length=255, verbose_name='Талон рақами')),
                ('reason_received', models.CharField(max_length=255, verbose_name='Олинган сабаби')),
                ('discipline_order', models.CharField(max_length=255, verbose_name='Интизомий жаза буйруқ рақами')),
                ('discipline_order_date', models.DateField(verbose_name='Интизомий жаза буйруқ санаси')),
                ('discipline_type', models.CharField(max_length=255, verbose_name='Интизомий жаза тури')),
                ('consequence_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Интизомий жаза оқибатида олиб қолинган пул миқдори')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Изоҳ')),
                ('date', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talon.branch', verbose_name='Филиал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talon.organization', verbose_name='Корхона')),
            ],
        ),
    ]
