# Generated by Django 5.0.6 on 2024-06-22 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talon',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='talon.organization', verbose_name='Корхона'),
        ),
    ]
