# Generated by Django 5.0.6 on 2024-06-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talon', '0002_alter_talon_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_organizations', to='talon.branch'),
        ),
    ]
